#!/usr/bin/env bash

# NOTE : USAGE help
if [ -z "$1" ]; then
echo ".
.
USAGE: msupercell \$FILE \$Sx \$Sy \$Sz
where  \$FILE  is the POSCAR file and \$Sx \$Sy \$Sz are supercell lengths....
.
.
" 
exit
fi





file=$1
supercell_size="$2 $3 $4"

# NOTE : create a temporary directory.
rm -rf .msupercell.tmp
mkdir  .msupercell.tmp
cp $file .msupercell.tmp/POSCAR
cd .msupercell.tmp

# NOTE : remove atom labels and Selective Dynamics info from POSCAR
line6=`awk "NR==6" POSCAR | awk '{print ($1*1)}'`
if [[ "$line6" = "0" ]]
then
alabels=`awk "NR==6" POSCAR`
sed '6d' POSCAR > POSCAR.new
mv POSCAR.new POSCAR
fi

line9=`awk "NR==9" POSCAR | awk '{print NF}'`
if [[ "$line9" = "6" ]]
then
awk "NR<7" POSCAR > POSCAR.new
awk "NR>7" POSCAR | awk '{print $1"  "$2"  "$3}' >> POSCAR.new
mv POSCAR.new POSCAR
fi

# NOTE : determine the number of atom types
ntypes=`awk "NR==6" POSCAR | awk '{print NF }'`

echo "
LSUPER =.T. (default)
NDIM   = $supercell_size 
NTYPES = $ntypes 
" > INPHON 

# NOTE : we need Dario Alfe's PHON program here !!!!!
# You can install PHON as explained in http://unam.bilkent.edu.tr/mt2/SIESTA-PHON/PHON/README.txt
phon

awk "NR<6" SPOSCAR >  POSCAR_$2_$3_$4
echo $alabels      >> POSCAR_$2_$3_$4
awk "NR>5" SPOSCAR >> POSCAR_$2_$3_$4

mv POSCAR_$2_$3_$4 ../s$file
cd ..
rm -rf .msupercell.tmp

