#!/bin/bash

case `arch` in

i686 )
vesta=/home/mt/Dropbox/bin/PROGRAMS/linux_VESTA-i686/VESTA ;;

x86_64 )
vesta=/home/mt/Dropbox/bin/PROGRAMS/linux_VESTA-x86_64/VESTA;;

esac



    file=` echo $1 | awk -F "/"  '{ print $NF }'`
  folder=` echo $1 | awk -F "/" '{ for (i = 1; i <= (NF-1); i++) printf("%s/", $i ) }'`


case $file in



*.xsf | *.xyz )
cd $folder
$vesta `pwd`/$file &
;;


relax.in | scf.in | nscf.in )
cd $folder
/home/mt/bin/QE/qe-main/PW/tools/pwi2xsf.sh `pwd`/$file >  `pwd`/$file.xsf
$vesta `pwd`/$file.xsf
rm -f `pwd`/$file.xsf
;;



* ) 
cd $folder
$vesta `pwd`/$file &
;;

esac


 




















 


# SILMEEEEE SILMEEEEEE

# file=$1
# math=`awk "NR==6" $file | awk '{print ($1*1)}'`
# 
# case $math in
# 0 ) # VASP5 file
#     scale=`awk  "NR==2" $file  | awk '{print $1}'`
#   lattice=`awk "NR==3,NR==5" $file  | awk -v "c=$scale" '{printf("%.10f \t" "\t%.10f \t" "\t%.10f" "\n",($1*c),($2*c),($3*c))}'`
#    labels=`awk "NR==6" $file ` ; ntypes=`awk "NR==7" $file | awk '{print NF}'`
#    natoms=`awk "NR==7" $file  | awk '{print ($1+$2+$3+$4+$5+$6+$7+$8+$9+$10)}'` ; math2=`echo $natoms + 8 | bc`
#      mode=`awk "NR==8" $file  | awk '{print $1}'`
#            awk "NR==9,NR==$math2" $file > .positions
# ;;
# 
# * ) # VASP4 file
#     scale=`awk  "NR==2" $file  | awk '{print $1}'`
#   lattice=`awk "NR==3,NR==5" $file  | awk -v "c=$scale" '{printf("%.10f \t" "\t%.10f \t" "\t%.10f" "\n",($1*c),($2*c),($3*c))}'`
#    labels=`awk "NR==6" $file ` ; ntypes=`awk "NR==7" $file | awk '{print NF}'`
#    natoms=`awk "NR==7" $file  | awk '{print ($1+$2+$3+$4+$5+$6+$7+$8+$9+$10)}'` ; math2=`echo $natoms + 8 | bc`
#      mode=`awk "NR==8" $file  | awk '{print $1}'`
#            awk "NR==9,NR==$math2" $file > .positions
# ;;
# 
# esac











# 
# 
# 
# 
# 
# existenceoffish=`echo $1 | grep "fish" | wc -l`
# 
# if [ $existenceoffish = "1" ]; then
# 
#   dosya=` echo $1 | awk -F "/"  '{ print $NF }'`
#   adres=` echo $1  | awk -F ":22" '{print $2}' |  awk -F "/" '{ for (i = 1; i <= (NF-1); i++) printf("%s/", $i ) }'`
#   user=`ps ux | grep mmatlab | grep fish | awk '{print $13}' | awk -F "@" '{print $1}' | awk -F "/" '{print $3}'`
#   ip=` echo $1  | awk -F "@" '{print $2}' | awk -F ":"  '{print $1}'`
# case $dosya in
# 
#   *.dat | *.m )
# 
#   rm -rf /home/mt/MATLAB/tmp1 ; mkdir /home/mt/MATLAB/tmp1 ; cd /home/mt/MATLAB/tmp1
#   scp $user@$ip:$adres/$dosya /home/mt/MATLAB/tmp1
#   scp $user@$ip:$adres/*.dat /home/mt/MATLAB/tmp1
#   scp $user@$ip:$adres/*.m /home/mt/MATLAB/tmp1
#   konqueror # --open-session mmatlab
# #   matlab -nosplash  -desktop
#   scp -r /home/mt/MATLAB/tmp1/* $user@$ip:$adres ;;
# 
#   * )
# 
#   adres=` echo $1  | awk -F ":22" '{print $2}' |  awk -F "/" '{ for (i = 1; i <= (NF); i++) printf("%s/", $i ) }'`
# 
#   rm -rf /home/mt/MATLAB/tmp1 ; mkdir /home/mt/MATLAB/tmp1 ; cd /home/mt/MATLAB/tmp1
#   scp  $user@$ip:$adres/*.dat /home/mt/MATLAB/tmp1
#   scp  $user@$ip:$adres/*.m /home/mt/MATLAB/tmp1
#   konqueror # --open-session mmatlab
# #  matlab -nosplash  -desktop
#   scp  /home/mt/MATLAB/tmp1/* $user@$ip:$adres ;;
# 
# esac
# 
# exit
# 
# fi
# 
# 
# 
# existenceofslash=`echo $1 | grep "/" | wc -l`
#   if [ $existenceofslash = "1" ]; then
#   cd $1
#   matlab -nosplash  -desktop
#   exit
#     else 
#     existenceofmfile=`echo $1 | grep ".m" | wc -l`
#     if [ $existenceofmfile = "1" ]; then
#     dosya=`echo "$1 " | awk -F ".m "  '{print $1}'`
#     echo "exit %deletethis" >> $1
#     matlab  -nodisplay -r $dosya
#     sed "/deletethis/d" <  $1 >  $1.new
#     mv $1.new $1
#     exit
#     fi
#   fi
# 
# existenceofarg1=`echo $1 | grep "/" | wc -l`
#   if [ $existenceofarg1 = "0" ]; then
#    matlab -nodisplay
#   fi
# # 
# #     cd $i
# #     matlab -desktop -nosplash
# # else
# # dosya=`echo $1 | awk -F ".m"  '{print $1}'`
# # matlab  -nodisplay -r $dosya 
# # fi
