#!/bin/bash

file_to_tar=$1

rm -rf $file_to_tar.zip   1>/dev/null 2>/dev/null
find . -maxdepth 1  -name $file_to_tar | xargs zip -rv $file_to_tar.zip  

if [ "$2" = "r" ]; then rm -rf $file_to_tar ; fi
