function mplot_altust(x1_data,x1_label,y1_data,y1_label,x2_data,x2_label,y2_data,y2_label)

figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,...
    'XColor',[0 0 0],...
    'YColor',[0 0 0],...
    'FontWeight','bold',...
    'FontSize',16,...
    'LineWidth',2,...
    'FontName','Times New Roman');

% Create line
line(x1_data,y1_data,'Parent',axes1,'MarkerFaceColor',[0 0 0],...
    'MarkerEdgeColor',[0 0 0],...
    'MarkerSize',10,...
    'Marker','square',...
    'LineWidth',3,...
    'LineStyle','-.',...
    'Color',[0 0 0]);

% Create xlabel
xlabel(x1_label,'FontWeight','bold','FontSize',18,'FontName','Times New Romans',...
    'Color',[0 0 0]);

% Create ylabel
ylabel(y1_label,'FontWeight','bold','FontSize',18,...
    'FontName','Times',...
    'Color',[0 0 0]);

x_axis_interval=(max(x1_data)-min(x1_data))/100;
y_axis_interval=(max(y1_data)-min(y1_data))/100;
x_axis_start=min(x1_data)-3*x_axis_interval ; 
x_axis_stop=max(x1_data)+3*x_axis_interval;
y_axis_start=min(y1_data)-3*y_axis_interval ; y_axis_stop=max(y1_data)+3*y_axis_interval;
axis([x_axis_start x_axis_stop y_axis_start y_axis_stop ]);


% Create axes
axes2 = axes('Parent',figure1,'YAxisLocation','right','XAxisLocation','top',...
    'XColor',[1 0 0],...
    'YColor',[0 0 0],...
    'FontWeight','bold',...
    'FontSize',16,...
    'LineWidth',2,...
    'FontName','Times New Roman',...
    'Color','none');


% Create line
line(x2_data,y2_data,'Parent',axes2,'MarkerFaceColor',[1 0 0],...
    'MarkerEdgeColor',[1 0 0],...
    'MarkerSize',10,...
    'Marker','square',...
    'LineWidth',3,...
    'LineStyle','-.',...
    'Color',[1 0 0]);

x_axis_interval=(max(x2_data)-min(x2_data))/100;
y_axis_interval=(max(y2_data)-min(y2_data))/100;
x_axis_start=min(x2_data)-3*x_axis_interval ; 
x_axis_stop=max(x2_data)+3*x_axis_interval;
y_axis_start=min(y2_data)-3*y_axis_interval ; y_axis_stop=max(y2_data)+3*y_axis_interval;
axis([x_axis_start x_axis_stop y_axis_start y_axis_stop ]);

%  % Create xlabel
%  xlabel(x1_label,'FontWeight','bold','FontSize',18,'FontName','Times',...
%      'Color',[1 0 0]);

% Create ylabel
ylabel(y1_label,'FontWeight','bold','FontSize',18,...
    'FontName','Times New Roman',...
    'Color',[0 0 0]);

%  filename = [ 'mplot_altust'];
%  print( '-r250','-depsc2',filename);



