#!/usr/bin/env python
# -*- coding: iso-8859-1 -*-



import numpy as np
import sys, os, time
import subprocess as sp
from io import open
from shutil import copyfile, rmtree

time.sleep(3)




# part-0
def make_common(inpfile,outfile):
    rmtree('Common',ignore_errors=True)    
    os.makedirs('Common', exist_ok=True)
    os.chdir('Common')
    copyfile('../'+inpfile,'./'+inpfile)
    if os.path.exists('../'+outfile):
        sp.call('$OCEAN_BIN/parse.pl --all ocean.in $OCEAN_BIN/oparse.h >> ../'+outfile, shell=True)
    else: sp.call('$OCEAN_BIN/parse.pl --all ocean.in $OCEAN_BIN/oparse.h > ../'+outfile, shell=True)
    sp.call('$OCEAN_BIN/defaults.pl >> ../'+outfile, shell=True)
    sp.call('$OCEAN_BIN/edges.pl >> ../'+outfile, shell=True)
    os.chdir('..')
    return

def make_common_silent(inpfile):
    rmtree('Common',ignore_errors=True)    
    os.makedirs('Common', exist_ok=True)
    os.chdir('Common')
    copyfile('../'+inpfile,'./'+inpfile)
    sp.call('$OCEAN_BIN/parse.pl --all ocean.in $OCEAN_BIN/oparse.h > /dev/null', shell=True)
    sp.call('$OCEAN_BIN/defaults.pl > /dev/null', shell=True)
    sp.call('$OCEAN_BIN/edges.pl > /dev/null', shell=True)
    os.chdir('..')
    return

# part-1
def make_opf(outfile):
    rmtree('OPF',ignore_errors=True)
    os.makedirs('OPF', exist_ok=True)
    os.chdir('OPF')
    print('running OPF')
    sp.call('echo -e :::::::::::::: OPF started @ `date` >> ../'+outfile, shell=True)    
    sp.call('$OCEAN_BIN/opf.pl >> ../'+outfile, shell=True)
    sp.call('echo -e :::::::::: OPF finished @ `date` >> ../'+outfile, shell=True)    
    print(' OPF finished')    
    os.chdir('..')
    return

# part-2
def make_dft(nthr,outfile):
    #rmtree('DFT',ignore_errors=True)    
    os.makedirs('DFT', exist_ok=True)
    os.chdir('DFT')
    print('running DFT')
    sp.call('echo -e :::::::::::::: DFT started @ `date` >> ../'+outfile, shell=True)
    sp.call('module unload cray-libsci; module load fftw; module load  espresso/6.1; export OMP_PLACES=threads; export OMP_PROC_BIND=spread; export OMP_NUM_THREADS='+str(int(nthr))+'; $OCEAN_BIN/dft.pl >> ../'+outfile, shell=True)
    sp.call('echo -e :::::::::: DFT finished @ `date` >> ../'+outfile, shell=True)   
    print(' DFT finished')      
    os.chdir('..')
    return

def make_dft_SCAN(nthr,outfile):
    rmtree('DFT',ignore_errors=True)    
    os.makedirs('DFT', exist_ok=True)
    os.chdir('DFT')
    print('running DFT')
    sp.call('echo -e :::::::::::::: DFT SCAN started @ `date` >> ../'+outfile, shell=True)
    sp.call('module unload cray-libsci; module load fftw; export OMP_PLACES=threads; export OMP_PROC_BIND=spread; export OMP_NUM_THREADS='+str(int(nthr))+'; $OCEAN_BIN/dft_SCAN.pl >> ../'+outfile, shell=True)
    sp.call('echo -e :::::::::: DFT SCAN finished @ `date` >> ../'+outfile, shell=True)   
    print(' DFT finished')      
    os.chdir('..')
    return


def serialize_prefix():
    sp.call('> ./Common/para_prefix', shell=True)    
    sp.call('echo nscf	1 > ./Common/pool_control', shell=True)
    sp.call('echo interpolate kpt	1 >> ./Common/pool_control', shell=True)
    sp.call('echo scf	1 >> ./Common/pool_control', shell=True)
    sp.call('echo obf	1 >> ./Common/pool_control', shell=True)
    sp.call('echo screen	1 >> ./Common/pool_control', shell=True)
    sp.call('echo interpolate screen	1 >> ./Common/pool_control', shell=True)    
    return

# part-3
def make_prep(outfile):
    rmtree('PREP',ignore_errors=True)      
    serialize_prefix()    
    os.makedirs('PREP', exist_ok=True)
    os.chdir('PREP')
    print('running PREP') 
    sp.call('echo -e :::::::::::::: PREP started @ `date` >> ../'+outfile, shell=True)    
    sp.call('$OCEAN_BIN/qe_dendip.pl >> ../'+outfile, shell=True)
    sp.call('echo -e :::::::::: PREP finished @ `date` >> ../'+outfile, shell=True)  
    print(' PREP finished')    
    os.chdir('..')
    return

# part-4
def make_screen(outfile):
    rmtree('SCREEN',ignore_errors=True)    
    serialize_prefix()    
    os.makedirs('SCREEN', exist_ok=True)
    os.chdir('SCREEN')
    print('running SCREEN')    
    sp.call('echo -e :::::::::::::: SCREEN started @ `date` >> ../'+outfile, shell=True)     
    sp.call('module unload cray-libsci; module load fftw; export OMP_PLACES=threads; export OMP_PROC_BIND=spread; export OMP_NUM_THREADS=1; $OCEAN_BIN/screen.pl >> ../'+outfile, shell=True)
    sp.call('echo -e :::::::::: SCREEN finished @ `date` >> ../'+outfile, shell=True)  
    print(' SCREEN finished')     
    os.chdir('..')

# part-5
def make_cnbse(outfile): 
    rmtree('CNBSE',ignore_errors=True)    
    serialize_prefix()    
    os.makedirs('CNBSE', exist_ok=True)
    os.chdir('CNBSE')
    print('running CNBSE') 
    sp.call('echo -e :::::::::::::: CNBSE started @ `date` >> ../'+outfile, shell=True)      
    sp.call('module unload cray-libsci; module load fftw; export OMP_NUM_THREADS=1; $OCEAN_BIN/cnbse_mpi.pl >> ../'+outfile, shell=True)
    sp.call('echo  >> ../'+outfile, shell=True)      
    sp.call('echo -e :::::::::: CNBSE finished @ `date` >> ../'+outfile, shell=True) 
    print(' CNBSE finished')    
    os.chdir('..')
    import mOCEAN; mOCEAN.readocean()
    return






# =================================================================== 
inputs = sys.argv

for a in range(len(inputs)):
    s=inputs[a].split('=')
    if s[0]   == 'part'  or s[0] == 'p'    : part = s[1]    
    elif s[0] == 'nth'   or s[0] == 'nthr' : nthr = int(s[1])  
    elif s[0] == 'node_per_job'   or s[0] == 'npj' : npj = int(s[1])  
    elif s[0] == 'cpu_per_job'   or s[0] == 'cpj' : cpj = int(s[1])      
    elif s[0] == 'input' or s[0] == 'i'    : inp  = s[1]    


try:
    part
except:
    ef = open('_ERROR', 'w')
    ef.write('\n ERROR: part unknown !!! Exiting.... \n')
    sys.exit('\n ERROR: part unknown !!! Exiting.... \n')    


try:
    inp
except:
    inp='ocean'
inpfile=inp+'.in'
outfile=inp+'.out'



try:
    nthr
except:
    nthr = []

try:
    cpj
except:
    cpj = []



# get number of available nodes
shout = sp.run(" env | grep SLURM_NNODES | awk -F = '{print $2}' ", 
                     shell=True, stdout=sp.PIPE, universal_newlines=True)
try:
    node_avail = int(shout.stdout.split()[0])
except:
    node_avail = 0 # probably this is a login node
    cpj = 1
    if not nthr: nthr = 1



# get hostname
host = os.uname()[1]
if  host[0:2] == 'ni':
    if not nthr: nthr = 2
    c = nthr*2; sc = ' -c'+str(int(c))
    os.environ['OCEAN_BIN'] = '/global/u2/t/topsakal/software/ocean/cori/hsw/OCEAN-2.1.1/'
    para_prefix = 'para_prefix{srun -n '+str(int(cpj))+sc+' '+'-N '+str(npj)+' } \n' 
    print(para_prefix)
elif  host[0:2] == 'co':
    if not nthr: nthr = 1
    node_avail = 1
    cpj = 1
    sc = ' ' 
    os.environ['OCEAN_BIN'] = '/global/u2/t/topsakal/software/ocean/cori/hsw/OCEAN-2.1.1/'
    para_prefix = '# \n' 
    print(para_prefix)    

          


def put_para_prefix(inpfile,para_prefix):        
    with open(inpfile, mode='r') as f:
        lines = f.readlines()    
    f = open("newfile.tmp","w")
    here=os.getcwd()
    f.write(para_prefix)
    for line in lines:
        if 'para_prefix' not in line:
            f.write(line)
    f.close()
    os.rename('newfile.tmp',inpfile)
    return



 
# ===================================================================  
if part == '0' or part == 'c':
    sp.call(' rm -rf CNBSE Common PAW NBSE PREP DFT SCREEN zWFN OPF absspct.png  ocean.out ocean_absspcts.dat *.npz ', shell=True)
    make_common(inpfile,outfile)

# ===================================================================  
if part == '1' or part == 'opf':
    make_opf(outfile)
    
# ===================================================================  
if part == '01' :
    sp.call(' rm -rf CNBSE Common PAW NBSE PREP DFT SCREEN zWFN OPF absspct.png  ocean.out ocean_absspcts.dat *.npz ', shell=True)
    make_common(inpfile,outfile)    
    make_opf(outfile)    
    
# ===================================================================  
if part == '2' or part == 'dft':
    put_para_prefix(inpfile,para_prefix)  
    make_common_silent(inpfile)
    make_dft(nthr,outfile)
    
if part == '2scan' or part == 'dftscan':
    put_para_prefix(inpfile,para_prefix)  
    make_common_silent(inpfile)
    make_dft_SCAN(nthr,outfile)    
       
# ===================================================================  
if part == '3' or part == 'prep':
    serialize_prefix()  
    make_prep(outfile)     
       
# ===================================================================  
if part == '4' or part == 'screen':
    serialize_prefix()    
    make_screen(outfile)  
       
# ===================================================================  
if part == '5' or part == 'cnbse':
    serialize_prefix()    
    make_cnbse(outfile)  
           
# ===================================================================  
if part == '345' or part == 'psc':
    serialize_prefix()  
    make_prep(outfile) 
    make_screen(outfile)     
    make_cnbse(outfile)      


# ===================================================================  
if part == '45' or part == 'sc':
    serialize_prefix()  
    make_screen(outfile)     
    make_cnbse(outfile)   


